### ISSUE TITLE
Reference material links?

### ISSUE THREAD

**Issue by miyu** [achlubek/venginenative#3]
Hey, love what you're doing! Out of curiosity, where do equations like those in https://github.com/achlubek/venginenative/blob/462985445ba418a8e469b27601dbc6ce9a14c83d/shaders/include/AtmScattering.glsl come from?

Are they derived by you, or are there, for example, papers you'd recommend so that I can learn more about what's happening? Same with how you're rendering, well, everything else.

**Comment by achlubek** [comment]
Hey!

I'm thrilled to hear that someone is interested in this project :)
Sorry that it took so long for me to respond, that part in particular -
which is rare in Vengine - is external, it is from there:
https://github.com/wwwtyro/glsl-atmosphere

I plan to replace this with my own scattering functions and work is going
on because this is very low quality and pretty slow.
If you want to implement this glsl-atmosphere, I have a hint for you - Do
it like I do it - render it to 128x128 cube map texture, 1 face at 1 frame,
this will make it almost no cost on frametime.
You can also make sMie parameter driven by fbm noise (and fbm noise driven
with ray-sphere intersection point, sphere being upper atmosphere) - This
can give really nice high clouds look.

Feel free to ask more questions!

Best regards,
Adrian


2017-05-02 23:43 GMT+02:00 Michael Yu <notifications@github.com>:

**Comment by miyu** [comment]
Thanks for the link! OOC why did you decide to switch away from C#? Were there significant performance issues or something?

**Comment by achlubek** [comment]
C# has very serious memory management problems and lacks support for
pointers. Also i wanted to learn c++

16.05.2017 10:45 AM "Michael Yu" <notifications@github.com> napisał(a):
